// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfuurjvwtnfkxrcxmhhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdXVyanZ3dG5ma3hyY3htaGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NTc4MTgsImV4cCI6MjA1NzEzMzgxOH0.GMzzZx50Blnk5nphB3NcUFpT_ko3uMuLJDx4Qk0cvR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);